# Project: 小明做生意最大化利润 GPT
# Makefile created by Dev-C++ 5.16

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
RES      = 小明做生意最大化利润_private.res
OBJ      = main.o $(RES)
LINKOBJ  = main.o $(RES)
LIBS     = -L"D:/应用/Dev-Cpp/MinGW64/lib" -L"D:/应用/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -g3
INCS     = -I"D:/应用/Dev-Cpp/MinGW64/include" -I"D:/应用/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/应用/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/8.1.0/include"
CXXINCS  = -I"D:/应用/Dev-Cpp/MinGW64/include" -I"D:/应用/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/应用/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/8.1.0/include" -I"D:/应用/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/8.1.0/include/c++"
BIN      = 小明做生意最大化利润.exe
CXXFLAGS = $(CXXINCS) -Wextra -g3 -pipe
CFLAGS   = $(INCS) -Wextra -g3 -pipe
RM       = del /q

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

小明做生意最大化利润_private.res: 小明做生意最大化利润_private.rc 
	$(WINDRES) -i 小明做生意最大化利润_private.rc --input-format=rc -o 小明做生意最大化利润_private.res -O coff 

