# Project: 字母异位词分组
# Makefile created by Dev-C++ 5.16

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = main.o
LINKOBJ  = main.o
LIBS     = -L"D:/Technology/Dev-Cpp/MinGW64/lib" -L"D:/Technology/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -g3
INCS     = -I"D:/Technology/Dev-Cpp/MinGW64/include" -I"D:/Technology/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/Technology/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/8.1.0/include"
CXXINCS  = -I"D:/Technology/Dev-Cpp/MinGW64/include" -I"D:/Technology/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/Technology/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/8.1.0/include" -I"D:/Technology/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/8.1.0/include/c++"
BIN      = 字母异位词分组.exe
CXXFLAGS = $(CXXINCS) -Wextra -g3 -pipe -std=c++11
CFLAGS   = $(INCS) -Wextra -g3 -pipe -std=c++11
RM       = del /q

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)
